name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Optional: Run on pull requests to 'main'

jobs:
  build:
    name: Build, Compress, and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]  # Build for both x86_64 and ARM64 architectures

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify your desired Go version

      # Step 3: Build the application
      - name: Do the honours
        run: |
          make release
