name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Optional: Run on pull requests to 'main'

jobs:
  build:
    name: Build, Compress, and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]  # Build for both x86_64 and ARM64 architectures

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify your desired Go version

      # Step 3: Build the application
      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

      - name: Compress and Upload Binary (Windows)
        if: matrix.os == 'windows'
        run: |
          # For Windows, create a .zip archive
          zip -j dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.zip dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.exe
          # Upload the .zip file
          echo "Uploading Windows .zip file"
          upload_file="dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.zip"
          curl -X POST -F "file=@$upload_file" https://api.github.com/repos/${{ github.repository }}/actions/artifacts

      - name: Compress and Upload Binary (Linux)
        if: matrix.os == 'linux'
        run: |
          # For Linux, create a .tar.gz archive
          tar -czvf dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C dist heimdahl-${{ matrix.os }}-${{ matrix.arch }}
          # Upload the .tar.gz file
          echo "Uploading Linux .tar.gz file"
          upload_file="dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          curl -X POST -F "file=@$upload_file" https://api.github.com/repos/${{ github.repository }}/actions/artifacts

      - name: Compress and Upload Binary (macOS)
        if: matrix.os == 'mac'
        run: |
          # For macOS, create a .tar.gz archive
          tar -czvf dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C dist heimdahl-${{ matrix.os }}-${{ matrix.arch }}
          # Upload the .tar.gz file
          echo "Uploading macOS .tar.gz file"
          upload_file="dist/heimdahl-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          curl -X POST -F "file=@$upload_file" https://api.github.com/repos/${{ github.repository }}/actions/artifacts
