name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Optional: Run on pull requests to 'main'

jobs:
  build:
    name: Build, Compress, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Specify your desired Go version



      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # or any dependencies you need

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64, windows/arm64'
          package: ''
          name: 'heimdahl'
          compress: 'true'
          dest: 'build'

      # Step 3: Build the application
      - name: Do the honours
        run: |
          ls -l build
